// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-sEUDPX3W4TWTXW-AwVOBpMoghn17R3o',
    appId: '1:404782147842:android:536de522ab7b75038dba1b',
    messagingSenderId: '404782147842',
    projectId: 'my-app-e6b61',
    databaseURL: 'https://my-app-e6b61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-app-e6b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUA3QHbIETGoXE8ZfGR97MCz3TixAMGk',
    appId: '1:404782147842:ios:9aa71c23f320d0468dba1b',
    messagingSenderId: '404782147842',
    projectId: 'my-app-e6b61',
    databaseURL: 'https://my-app-e6b61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-app-e6b61.appspot.com',
    androidClientId: '404782147842-uj3nl5pogco6ca783g52ch459etafka3.apps.googleusercontent.com',
    iosClientId: '404782147842-10h4urhfaka43nkpbl7uln8puvnl6q8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatorMind',
  );
}
